"""add pos customer fields

Revision ID: 256c07632736
Revises: 7952c5122108
Create Date: 2026-07-08 08:38:56.574857

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '256c07632736'
down_revision: Union[str, None] = '7952c5122108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pos_sales', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('pos_sales', sa.Column('walk_in_name', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'pos_sales', 'users', ['customer_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('stock_transactions_created_by_id_fkey', 'stock_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'stock_transactions', 'internal_users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_transactions', type_='foreignkey')
    op.create_foreign_key('stock_transactions_created_by_id_fkey', 'stock_transactions', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'pos_sales', type_='foreignkey')
    op.drop_column('pos_sales', 'walk_in_name')
    op.drop_column('pos_sales', 'customer_id')
    # ### end Alembic commands ###
