"""Change StockTransaction FK to users

Revision ID: 353acf88972a
Revises: 74fa0a211316
Create Date: 2026-07-07 19:46:50.237684

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '353acf88972a'
down_revision: Union[str, None] = '74fa0a211316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stock_transactions_created_by_id_fkey', 'stock_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'stock_transactions', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_transactions', type_='foreignkey')
    op.create_foreign_key('stock_transactions_created_by_id_fkey', 'stock_transactions', 'internal_users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
