"""add variant image_url

Revision ID: 52bdaba5c067
Revises: cdc14e9367df
Create Date: 2026-07-11 22:24:05.079184

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '52bdaba5c067'
down_revision: Union[str, None] = 'cdc14e9367df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'sales_returns', 'journals', ['journal_id'], ['id'])
    op.create_foreign_key(None, 'sales_returns', 'sales_invoices', ['invoice_id'], ['id'])
    op.create_foreign_key(None, 'stock_transactions', 'product_variants', ['variant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'stock_transactions', 'internal_users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'vendors', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='foreignkey')
    op.drop_constraint(None, 'stock_transactions', type_='foreignkey')
    op.drop_constraint(None, 'stock_transactions', type_='foreignkey')
    op.drop_constraint(None, 'sales_returns', type_='foreignkey')
    op.drop_constraint(None, 'sales_returns', type_='foreignkey')
    op.drop_column('product_variants', 'image_url')
    # ### end Alembic commands ###
