"""add pos tables

Revision ID: 74fa0a211316
Revises: 7f6fe4f2e354
Create Date: 2026-07-07 17:52:57.559507

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '74fa0a211316'
down_revision: Union[str, None] = '7f6fe4f2e354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pos_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_number', sa.String(length=30), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('completed', 'voided', name='possalestatus'), nullable=False),
    sa.Column('cashier_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cashier_id'], ['internal_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pos_sales_sale_number'), 'pos_sales', ['sale_number'], unique=True)
    op.create_table('pos_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pos_sale_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('cash', 'card', 'upi', name='pospaymentmethod'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pos_sale_id'], ['pos_sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pos_sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pos_sale_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('variant_sku', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pos_sale_id'], ['pos_sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pos_sale_items')
    op.drop_table('pos_payments')
    op.drop_index(op.f('ix_pos_sales_sale_number'), table_name='pos_sales')
    op.drop_table('pos_sales')
    # ### end Alembic commands ###
