"""fix stock_transactions created_by fk to internal_users

Revision ID: 7f6fe4f2e354
Revises: ae180acffb4e
Create Date: 2026-07-02 21:27:30.975987

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7f6fe4f2e354'
down_revision: Union[str, None] = 'ae180acffb4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'sales', 'inventory', name='internalrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_users_email'), 'internal_users', ['email'], unique=True)
    op.create_index(op.f('ix_internal_users_phone'), 'internal_users', ['phone'], unique=True)
    op.drop_constraint('stock_transactions_created_by_id_fkey', 'stock_transactions', type_='foreignkey')

    # Clear stale created_by_id values pointing at old users.id — internal_users is a new,
    # separate table and those ids don't correspond to any internal user.
    op.execute("UPDATE stock_transactions SET created_by_id = NULL")

    op.create_foreign_key(None, 'stock_transactions', 'internal_users', ['created_by_id'], ['id'], ondelete='SET NULL')
    

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_transactions', type_='foreignkey')
    op.create_foreign_key('stock_transactions_created_by_id_fkey', 'stock_transactions', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_internal_users_phone'), table_name='internal_users')
    op.drop_index(op.f('ix_internal_users_email'), table_name='internal_users')
    op.drop_table('internal_users')
    # ### end Alembic commands ###
