"""add auto backup settings to company_settings

Revision ID: cdc14e9367df
Revises: e6ac2af2ec22
Create Date: 2026-07-11 18:36:32.644741

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cdc14e9367df'
down_revision: Union[str, None] = 'e6ac2af2ec22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_settings', sa.Column('auto_backup_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('company_settings', sa.Column('auto_backup_time', sa.String(length=5), nullable=False, server_default='02:00'))
    op.add_column('company_settings', sa.Column('auto_backup_retention_days', sa.Integer(), nullable=False, server_default='7'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_settings', 'auto_backup_retention_days')
    op.drop_column('company_settings', 'auto_backup_time')
    op.drop_column('company_settings', 'auto_backup_enabled')
    # ### end Alembic commands ###
