"""make trade_price nullable

Revision ID: d65b576fe4f7
Revises: e3f543c5edd2
Create Date: 2026-07-07 10:21:16.328274

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd65b576fe4f7'
down_revision: Union[str, None] = 'e3f543c5edd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_variants', 'trade_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_variants', 'trade_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###
