"""fix stock transaction foreign key

Revision ID: ed11b94f8072
Revises: 353acf88972a
Create Date: 2026-07-07 20:08:46.516313

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ed11b94f8072'
down_revision: Union[str, None] = '353acf88972a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
